site_name: 'Backstage Dependency Check plugin'
site_description: 'Dependency Check management for Backstage'

nav:
  - Home: index.md
  - Setup: setup.md
  - 'Integration with @backstage/plugin-search': search.md

plugins:
  - techdocs-core
