name: 'Code Improvements'
description: 'Use it for create issues about code improvements'
labels: ['enhancement']
body:
  - type: 'markdown'
    attributes:
      value: |
        Thanks for creating an issue 😄!

        Please search open/closed issues before submitting. Someone
        might have asked the same thing before 😉!

        We're all volunteers here, so help us help you by taking the time to
        accurately fill out this template. ❤️
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      description: 'A brief description of the improvement needed'
      placeholder: |
        I suggest _____ improvement due to ____.
    validations:
      required: true
  - type: 'checkboxes'
    id: 'plugin-type'
    attributes:
      label: 'Plugin'
      description: 'The plugin affected'
      options:
        - label: 'library check frontend'
        - label: 'library check backend'
  - type: 'textarea'
    id: 'additional-information'
    attributes:
      label: 'Additional Information'
      description: |
        Use this section to provide any additional information you might have
        like screenshots, notes, or links to ideas.
